### ISSUE TITLE
Emurgo: TexDecoder is not a constructor

### ISSUE THREAD

**Issue by seamossonline** [MeshJS/mesh#54]
![Screenshot 2022-11-29 205116](https://user-images.githubusercontent.com/10775017/204710628-f76018c0-4738-4a14-b8d1-8fe44f5ae51e.png)
![textdecoder is not a constructor](https://user-images.githubusercontent.com/10775017/204710642-c32681f2-fc7a-4fea-b165-3571a3141633.png)

I am attempting to implement @martifylabs/mesh on a Vue project.  The line...

import { BrowserWallet } from '@martifylabs/mesh';

immediately starts causing issues. This one in particular, it seems like mesh.js is using TextDecoder from the cardano-serialization-library-nodejs.js in an unexpected way.

Should I be using a different version of mesh (see screenshot)? What version of Node do you recommend?

**Comment by abdelkrimdev** [comment]
Hey, 😄 I was able to reproduce the issue on my end, and it turns out the culprit here is `Vite`.
Vite is loading the Node version of the CSL on Browser which is not correct.
I tried to reach out to them via Discord and with some examples, they were able to identify the bug, here is a PR
https://github.com/vitejs/vite/pull/11219 which fixes the issue.
as a temporary fix, you can use Webpack instead.

**Comment by seamossonline** [comment]
> Hey, 😄 I was able to reproduce the issue on my end, and it turns out the culprit here is `Vite`. Vite is loading the Node version of the CSL on Browser which is not correct. I tried to reach out to them via Discord and with some examples, they were able to identify the bug, here is a PR [vitejs/vite#11219](https://github.com/vitejs/vite/pull/11219) which fixes the issue. as a temporary fix, you can use Webpack instead.

Awesome! That was going to be my next question -- how do you migrate a project from Vite to Webpack?

**Comment by denishacquin** [comment]
Would really appreciate a fix on this :/
